# Generated by Django 5.1.6 on 2025-03-03 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investment_amount_zar', models.DecimalField(decimal_places=2, max_digits=20)),
                ('btc_volume', models.DecimalField(decimal_places=8, max_digits=20)),
                ('bybit_price_usd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('valr_price_zar', models.DecimalField(decimal_places=2, max_digits=20)),
                ('usd_zar_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('premium_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit_zar', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('bybit_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('valr_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bybit_price_usd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('valr_price_zar', models.DecimalField(decimal_places=2, max_digits=20)),
                ('btc_volume', models.DecimalField(decimal_places=8, max_digits=20)),
                ('spread_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='bot.trade')),
            ],
        ),
    ]
